name: field_suggestion
description: Create highly customizable, simple, and controllable autocomplete fields.
version: 0.2.3
homepage: https://github.com/theiskaa/field_suggestion
issue_tracker: https://github.com/theiskaa/field_suggestion/issues
documentation: https://github.com/theiskaa/field_suggestion/wiki

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  highlightable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
